#!/usr/bin/ruby

# read input
input = ARGF.read

# create tmp file
tmpFile = File.new('/tmp/textplay_pagecheck.txt', "w+")

# dump the input into that file
File.open('/tmp/textplay_pagecheck.txt', "w+") do |txtFile|
txtFile.puts input
end

# run textplay
system("~/code/textplay/textplay -p /tmp/textplay_pagecheck.txt /tmp/textplay_pagecheck.pdf;open /tmp/textplay_pagecheck.pdf")

# put the input back to STDOUT
puts input